### ISSUE TITLE
Chroma map 1e330 is broken af

### ISSUE THREAD

**Issue by Jd-Gamer65** [bsq-ports/Chroma#13]
https://user-images.githubusercontent.com/72290220/147389795-ca41c6df-681e-4987-b8a9-83d3e22d40db.mp4

Sorry if this isn't the most detailed bug report. I'm literally writing this from my quest. 

This map uses the Billie Eilish environment which might affect it, idk

Or maybe it's my unorthodox way of enforcing that platform using environment removals

(i'm leaning towards the latter)

**Comment by Fernthedev** [comment]
Uses Billie environment which is not supported.
