### ISSUE TITLE
Chroma making in-game modifers not work

### ISSUE THREAD

**Issue by jmaeshawn** [bsq-ports/Chroma#16]
I was told to file an issue here because after I'm having a problem where the default in-game modifiers like No Fail and No Arrow don't work whenever Chroma is installed and active on Beat Saber 1.24.

The only mods I have installed are:
Core Mods
Paperlog
Tracks
CustomJSONData
Chroma 

Whenever Chroma is installed and turned on, I still fail and the blocks still have arrows even though the two in-game modifiers are turned on. But when Chroma is disabled, No Fail and No Arrows work properly.

Please fix this bug. Thank you in advance.

**Comment by jmaeshawn** [comment]
I now completely uninstalled Chroma and its dependencies, and then installed NoodleExtensions (which reinstalls the same dependencies).

The same problem still happens where I fail and the blocks have arrows even when No Fail and No Arrows is turned on. 

So I wonder if the bug is with the 3 dependencies (Paperlog, Tracks, CustomJSONData) rather than Chroma itself.

**Comment by Fernthedev** [comment]
I do not experience this bug myself as I have been testing for months with No Fail enabled.

**Comment by jmaeshawn** [comment]
> I do not experience this bug myself as I have been testing for months with No Fail enabled.

Thank you for replying so quickly.

Have you tried it with the No Arrows enabled? I've even gone as far as completely uninstalling and reinstalling Beat Saber and then re-modding it, and the problem still persists.

**Comment by Fernthedev** [comment]
No arrows is deemed a bug, no idea why it doesn't work
