### ISSUE TITLE
Game Crash (With Logs)

### ISSUE THREAD

**Issue by BoogieHasFun** [bsq-ports/Chroma#2]
[Chroma_2_4_10q1.log](https://github.com/bsq-ports/Chroma/files/7024135/Chroma_2_4_10q1.log)

**Comment by Fernthedev** [comment]
Please post the tombstone or `adb logcat` logs

**Comment by BoogieHasFun** [comment]
I have no idea how to get those logs.

**Comment by Fernthedev** [comment]
tombstone would be in the parent directory of the logs you uploaded right now. Feel free to upload all 3

**Comment by BoogieHasFun** [comment]
ima put that on a mediafire link because github wont let me post the files

**Comment by BoogieHasFun** [comment]
https://www.mediafire.com/folder/abr2xc60pmbxh/logs

**Comment by Fernthedev** [comment]
This crash indicates custom json data is giving wrong information. Please try reinstall the qmod or game

**Comment by BoogieHasFun** [comment]
Did both, maybe other mods?
Or maybe just the song I'm playing doesn't work with this mod, (the map changes block colors)

**Comment by Fernthedev** [comment]
Please send the map then

**Comment by BoogieHasFun** [comment]
https://beatsaver.com/maps/bb27

**Comment by Fernthedev** [comment]
I am unable to reproduce the crash. I will be closing this, you may try this [though](https://github.com/bsq-ports/Chroma/releases/tag/2.4.10q2).

**Comment by BoogieHasFun** [comment]
also looks like some mods mess up pinkcore pinkcore, chroma might be the mod that causes this.

**Comment by Fernthedev** [comment]
I can assure you Chroma is not the cause of PinkCore bugs, at least not directly.

**Comment by BoogieHasFun** [comment]
chroma turns off the names on the song with pinkcore, im pretty sure pinkcore is messing things up or the other way around

**Comment by jakearchibald** [comment]
> chroma turns off the names on the song (eg. Chroma Map [Player], but [Player] isnt there) with pinkcore

I'm experiencing the same thing, then a crash at the start of each song. I'll try uninstalling and reinstalling.

**Comment by Fernthedev** [comment]
Looking at the crash, it seems to resemble #4. The fix is already implemented though waiting merge at StackDoubleFlow/CustomJSONData#9. Wait patiently :)
