### ISSUE TITLE
Chroma won't load

### ISSUE THREAD

**Issue by lordlad** [bsq-ports/Chroma#21]
Installed the latest version of Chroma over the last one (v2.6.0 to v2.6.1) and now it won't loaded with the following error:

"libchroma.so didn't load because dlopen failed - cannot locate symbol
![com beatgames beatsaber-20220820-152700](https://user-images.githubusercontent.com/2647193/185734750-b26c19f8-ac02-4bd9-ab95-e5bedb76b751.jpg)

**Comment by Fernthedev** [comment]
Update your coremods
