### ISSUE TITLE
Environment object removal doesn't work properly #28

### ISSUE THREAD

**Issue by JonnyVR1** [bsq-ports/Chroma#23]
Example map, Porter Robinson - Shelter https://bsaber.com/songs/1ad55/

The equaliser bars on the left and right sides are removed on the PC version, present in Quest. I believe the wanted behaviour here is to have them removed
![com beatgames beatsaber-20220821-144011](https://user-images.githubusercontent.com/949967/185793754-b7fd2465-8fcd-4085-b3b4-87c326f14428.jpg)

**Comment by Fernthedev** [comment]
Ensure you don't have environment override enabled and to have environment enhancements are enabled.

**Comment by JonnyVR1** [comment]
![com beatgames beatsaber-20220821-144430](https://user-images.githubusercontent.com/949967/185793923-9aae8e58-6812-49a5-bb93-775089e9d7b3.jpg)
![com beatgames beatsaber-20220821-144452](https://user-images.githubusercontent.com/949967/185793925-fd52ee71-bbec-4a18-bc96-90f2e73279be.jpg)

**Comment by Fernthedev** [comment]
Environment enhancements are working as intended. This a mapper error, see here on latest PC version 
![image](https://user-images.githubusercontent.com/15272073/186971286-9ff7528c-ab55-43a2-a438-60388e0f070b.png)
