### ISSUE TITLE
Ring Lights Crash/Lack of functionality

### ISSUE THREAD

**Issue by Manleyne** [bsq-ports/Chroma#24]
These maps (and others not listed) crash when similar ring light events happen. (the rare times it doesn’t crash, the rings will not light up anyway)

- https://beatsaver.com/maps/d995

- https://beatsaver.com/maps/ed2a

- https://beatsaver.com/maps/d299

Log of a crash (specially of highscore):
[adb.log](https://github.com/bsq-ports/Chroma/files/9403007/adb.log)

**Comment by grimy192837465** [comment]
Is this what is causing the below song to crash around 20 or 30 seconds in so you know? Would be great if you could test it to see if it’s the same result for you. Thanks

https://beatsaver.com/maps/14d64

**Comment by Fernthedev** [comment]
Fixed in 6b0e75b19fc7dfb2c04c7a4beabb81f9c0f97712
