### ISSUE TITLE
Excessive lag on chroma enabled maps

### ISSUE THREAD

**Issue by JMarty** [bsq-ports/Chroma#25]
Really appreciate your work and effort.

Chroma enabled maps seems to lag and freeze for seconds. Example: Marnik - Hocus Pocus, Up & Down, etc.

**Comment by Fernthedev** [comment]
Unable to reproduce

**Comment by jonathonf** [comment]
I see this too, generally at the very start of the map there will be a good second or two freeze, then an occasional stutter during the rest of the track.
