### ISSUE TITLE
Background not visible

### ISSUE THREAD

**Issue by Paultje52** [bsq-ports/Chroma#26]
After I installed the latest version of the mod on the latest beat saber version (1.24), the song `Somewhere Out There` doesn't look like it  should look. Everything worked fine in a previous version (1.17.1 with chroma 2.5.7).

This is how it looks like when I use the map
![2119](https://user-images.githubusercontent.com/31313717/187032460-8895ed31-0746-4559-88ea-335fbc13b269.jpg)
And this is what it should look like (from [here](https://www.youtube.com/watch?v=JxCmOOSJRW4)).
![image](https://user-images.githubusercontent.com/31313717/187032479-5f469990-1519-414f-a764-2146f7e6336b.png)

This issue is also present after restarting my quest 2. The chroma version I'm currently using is 2.6.4.

Some issues are also present in other maps. In Someone Else's Hat, the color doesn't change to red. In the previous version the color changed like it should.

**Comment by Fernthedev** [comment]
Unable to reproduce, tried `Somewhere out there` 1 hour ago. Make sure you don't have environment override enabled or walls disabled

**Comment by Paultje52** [comment]
I found out why the issue is present: somehow the environment effects were turned off when updating. You can turn this on under `Player Settings`. Everything now looks how it should look like.

**Comment by justindijkshoorn** [comment]
> I found out why the issue is present: somehow the environment effects were turned off when updating. You can turn this on under `Player Settings`. Everything now looks how it should look like.

Thanks, i had the same issue! Turning on all environment effects in player settings fixed it 👍.
