### ISSUE TITLE
Color Alpha Being Incorrect

### ISSUE THREAD

**Issue by Manleyne** [bsq-ports/Chroma#28]
On some specific maps, hitting some notes will cause the alpha on the saber to be set incorrectly (either as low as it can go or as high as it can go)

- https://beatsaver.com/maps/23f6b: The notes at the very start, and later on.
- https://beatsaver.com/maps/ed2a: Any note that changes color.
- More I am forgetting.

Example: https://streamable.com/rg9nq2

Normally only the handle and trails are affected, but with bloom on, the entire saber will be changed.

Wether the alpha is super low or super high seems to be random. It is consistently low on your first playthrough of those maps, but playing them multiple times can have different results.

**Comment by Fernthedev** [comment]
I actually allowed this behavior intentionally but I'll disable it since it seems nauseous.
