### ISSUE TITLE
Chroma and PinkCore

### ISSUE THREAD

**Issue by AwesomeCE110** [bsq-ports/Chroma#3]
It seems as though the new Chroma mod and PinkCore are having some compatibility issues (at least for me), w/o Chroma, mapper names show up, and w/ it, they are gone, I am also reporting this issue to Pink, I hope you can figure this out. (I suspect ChromaLite may not be fully removed, but that's just a thought)

**Comment by Fernthedev** [comment]
PinkCore was written from the ground up and planned to have no interaction with Chroma or ChromaLite. The only way these two mods interact are with Requirements/Suggestions. I suggest report this bug as a PinkCore bug

**Comment by KleaTech** [comment]
Please do some investigation on this. When I have the Chroma mod enabled, the mapper names are not visible.
![com beatgames beatsaber-20210830-222904](https://user-images.githubusercontent.com/24510869/131401416-7d8fa8b3-b9f0-4a32-8a7c-88ca33e87a3a.jpg)
![com beatgames beatsaber-20210830-222753](https://user-images.githubusercontent.com/24510869/131401419-3783aa41-c71d-4f4a-98bf-1e05934595be.jpg)
