### ISSUE TITLE
Chroma crashing on 1.24 on the map "curses" by swifter (2980e)

### ISSUE THREAD

**Issue by oli-ctrl** [bsq-ports/Chroma#30]
## Chroma crashing on 1.24 on the map "curses" by swifter (2980e)
Crashes on song start, Tested on multiple different headsets 
The crash is consistent and other mods don't effect it, This log is from @Adomi#5111 on discord. 
[logcat (1).log](https://github.com/bsq-ports/Chroma/files/9490451/logcat.1.log)

**Comment by Fernthedev** [comment]
Already fixed
