### ISSUE TITLE
1015

### ISSUE THREAD

**Issue by Manleyne** [bsq-ports/Chroma#36]
The platform at 1:03 in [this map](https://beatsaver.com/maps/1f304) can be seen misaligned, placed too far forwards, and never going away after it is supposed to.

![3C22E7B2-32F8-4D37-8160-0F8C264CE433](https://user-images.githubusercontent.com/83431062/201202922-b02a9083-0583-431d-94da-9abd8dc4b56c.jpeg)

**Comment by Fernthedev** [comment]
I believe this was fixed. Feel free to close if that's the case

**Comment by Manleyne** [comment]
still happens

**Comment by Fernthedev** [comment]
![image](https://github.com/bsq-ports/Chroma/assets/15272073/9c44b76f-e9f9-427a-8d71-6db86bdcc8c4)
Fixed? :)

**Comment by Manleyne** [comment]
fixed!
