### ISSUE TITLE
Make a wish

### ISSUE THREAD

**Issue by Manleyne** [bsq-ports/Chroma#38]
The front of the platform in [this map](https://beatsaver.com/maps/1a32d) does not get moved when it is supposed to (at 2:15).

![5F2CF8A4-2560-49A7-8CC4-0A88527930BE](https://user-images.githubusercontent.com/83431062/201204814-2b3ab47f-1714-4ac1-b36b-d01ef874013f.jpeg)

**Comment by Fernthedev** [comment]
Fixed sometime ago
