### ISSUE TITLE
Should I expect a mod for 1.27.0 ?

### ISSUE THREAD

**Issue by Andrey446** [bsq-ports/Chroma#39]

**Comment by AKASGaming** [comment]
Posting issues like these discourage devs from continuing

**Comment by Silver-Volt4** [comment]
> Posting issues like these discourage devs from continuing

Begging for a release, sure, but a GitHub issue? That at least allows other people to track the update's release.

**Comment by BoogieHasFun** [comment]
it will come Soon™️
just let Fern do whatever he needs to do

**Comment by st-ivan** [comment]
patiently waiting

**Comment by chavinlo** [comment]
same here

**Comment by AByakugans** [comment]
Same here pls @Fernthedev save us! Thank you a milion!

**Comment by Silver-Volt4** [comment]
> Same here pls Fernthedev save us! Thank you a milion!

oh my goodness can you NOT? he has a life to live. the mod will come eventually. there's no need to whine for it like that

**Comment by Fernthedev** [comment]
Updated to 1.28.0
