### ISSUE TITLE
Chroma Obstacle API bug

### ISSUE THREAD

**Issue by NuggoDEV** [bsq-ports/Chroma#43]
Heya!

When using the latest version of the Chroma API I have found that when colouring all walls at once using the `setAllObstacleColorSafe` method doesn't actually colour the walls, instead leaving them as the user's set colour. I can confirm the colour I'm using is valid as well due to me using the same function for setting the notes, bombs and lights.

Link to what I'm doing [here](https://github.com/NuggoDEV/Technicolour/blob/main/src/Hooks/GradientColour.cpp#L113).

*also off topic but slight problem with lighting. Either I can't figure out how to do the light colouring for events or the same problem is happening here as with the walls, link to the light stuff [here](https://github.com/NuggoDEV/Technicolour/blob/main/src/Hooks/RandomColour.cpp#L82).*

**Comment by Fernthedev** [comment]
The only thing I can think of at the moment is that your color set is running too early, therefore the color is being reset when the obstacle is spawned.

Try coloring the obstacle later in its lifetime, at this time I can't suggest where.

**Comment by NuggoDEV** [comment]
Yeah I actually just figured out what the cause of this was, I was being an absolute idiot and was checking if the light value was set to gradient instead of if the wall value was. 🤦
