### ISSUE TITLE
 Chroma causes issues with 360 playability

### ISSUE THREAD

**Issue by LaidBackAries** [bsq-ports/Chroma#50]
With Chroma installed/activated but even if it's turned off in game it still causes the issue. While playing 360 the lane lights/ triangles don't light up so blocks will come from surprise locations. I got it to work once i disabled Chroma in BMBF.
Standalone Quest modded 1.28

**Comment by LaidBackAries** [comment]
Updating for an FYI that the issue is either with both Chroma and Noodle Extensions or is with the file "Tracks" that comes with both.  I was only using one at a time and discovered this to be the case after recently installing Noodle (after I stopped using Chroma).

**Comment by Fernthedev** [comment]
Duplicate of https://github.com/StackDoubleFlow/CustomJSONData/issues/35
