### ISSUE TITLE
Fix v2 events(1.35)

### ISSUE THREAD

**Issue by Futuremappermydud** [bsq-ports/Chroma#55]
After updating to 1.35 v2 chroma lighting no longer works. Seems to be because Awake() and Start() were merged? Custom data may also not be set, need to check both.

**Comment by Futuremappermydud** [comment]
> Any more information on this? Been learning c++ for personal projects but figure I could take a look at least
you can try building stuff for yourself. I havnt touched it for a second but even for me its very confusing. Not much more information i can give because i honestly have no idea what has broken.

**Comment by ThePizzaMill** [comment]
No worries! Where should I start looking to get a grasp on how Chroma works?

**Comment by Fernthedev** [comment]
> No worries! Where should I start looking to get a grasp on how Chroma works?

Pretty much anywhere. Don't expect friendly documentation for anything, just read [the wiki](https://github.com/Aeroluna/Heck/wiki) and start looking around.

It's probably related to ChromaLightSwitchEventEffect or deserializing basic events.

**Comment by Fernthedev** [comment]
Resolved
