### ISSUE TITLE
Saber Coloring doesn't work with custom sabers and trails.

### ISSUE THREAD

**Issue by BoogieHasFun** [bsq-ports/Chroma#8]
I'll be playing (for example) "Fruit Ninja (but in beat saber)" and my saber colors won't change while hitting a different colored block like their supposed to.

But with default sabers they change but the trail doesn't.

> Video: Coming Soon.

> Logs: https://github.com/BoogieHasFun/BoogieQuestLogs/releases/tag/0.1

**Comment by Fernthedev** [comment]
No logs, no videos, no steps to reproduce. This if anything is a Qosmetics bug that I am not experiencing either.

**Comment by BoogieHasFun** [comment]
looks like some people cant read.
i was going to get s video and adb logcat + tombstone logs in a couple hours

**Comment by BoogieHasFun** [comment]
this might be stupid but logs are posted [here.](https://github.com/BoogieHasFun/BoogieQuestLogs/releases/tag/1.0)

**Comment by Fernthedev** [comment]
With all due respect, you should not make an issue and provide vital information later as it wastes people's time and patience. Also, you never mentioned you were crashing? Why are you giving me crash logs if it's just saber coloring not working? If your intention was to provide logs, I suggest you to get an `adb logcat` instead. The BSMG server's `#quest-help` channel can help you with this if need be.

I also suggest to try other sabers and run without Qosmetics. I've experienced some sabers with some weird trail coloring which may be the case here.

**Comment by BoogieHasFun** [comment]
sorry, im dumb and have never done stuff like this

**Comment by BoogieHasFun** [comment]
i copied the logs from powershell onto a text file. so [here it is.](https://github.com/BoogieHasFun/BoogieQuestLogs/releases/tag/0.1)

**Comment by BoogieHasFun** [comment]
i can confirm its Qosmetics, because without it works fine.
